stages:
  - test

test:
  image: python:2.7-jessie
  services:
    - couchdb:1.6
  tags:
    - kube
  script:
    - apt-get update -y && apt-get install libsodium-dev -y
    - git clone https://github.com/ProzorroUKR/openprocurement.api.git src/openprocurement.api
    - pip install -r src/openprocurement.api/requirements.txt
    - pip install -e src/openprocurement.api[test]
    - pip install -e .[test]
    - sleep infinity
    - py.test --cov openprocurement.concord openprocurement/ -v
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
