language: python
sudo: required
before_script:
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get -qq update
  - sudo apt-get install libsodium13 -y
python:
  - "2.7"
services:
  - couchdb
env:
  - TZ=Europe/Kiev
cache:
  directories:
    - eggs
install:
  - git clone https://github.com/ProzorroUKR/openprocurement.api.git src/openprocurement.api
  - pip install -r src/openprocurement.api/requirements.txt
  - pip install -e src/openprocurement.api[test]
  - pip install -e .[test]
script:
  - CONCORD_COUCHDB_URL=http://op:op@localhost:5984/ nosetests
after_success:
  - coveralls
